language: dart
dart:
  - stable
os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
    packages:
      - libstdc++6
      - fonts-droid-fallback
install:
  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - cd $TRAVIS_BUILD_DIR
  - flutter packages get
  - flutter analyze --no-pub --no-current-package lib
  - flutter test
  - flutter packages pub publish --dry-run
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.pub-cache